# version: '3'

# services:
#   # Database
#   db:
#     image: mysql
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: root

version: '3.1'

services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - db-mysql:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-mysql:
